---
# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "yarn"
      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: ESLint
        run: yarn lint

      - name: Prettier
        run: yarn prettier --check .

      - name: Check docs
        run: node ./scripts/check-doc.js

      - name: Check build JSDoc
        run: yarn jsdoc 1> /dev/null

      - name: Check commit messages
        if: startsWith( github.event.head_commit.message, 'VER' )
        env:
          COMMIT_MSG: ${{ toJson(github.event.commits.*.message) }}
        run: |
          node ./node_modules/exlg-git-commit-msg-std/check.js -c "$PWD/.gitmsgrc.cjs" -e COMMIT_MSG
